---
- hosts: windows
  become: yes
  gather_facts: false
  tasks:
    - name: Download python 3 installer.
      win_get_url:
        url: 'https://www.python.org/ftp/python/3.10.4/python-3.10.4-amd64.exe'
        dest: 'C:\temp\pkgs\python3\python-3.10.4-amd64.exe'

    - name: Install python 3.
      win_package:
        path: 'C:\temp\pkgs\python3\python-3.10.4-amd64.exe'
        arguments: /quiet /PrependPath=1 /InstallAllUsers=1
        state: present

    - name: Clean up the package directory.
      ansible.windows.win_powershell:
        script: |
          Remove-Item -Path "C:\temp\pkgs\python3" -Recurse -Force


- hosts: linux
  become: yes
  tasks:
    - name: Check if python is installed.
      yum: name=python state=present
